const mongoose=require('mongoose')

const orderSchema= new mongoose.Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    },
    orderNumber:{
        type:String,
        required:true,
        unique:true
    },
    items:[{
        productId:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"Product",
            required:true
        },
        productName:{
            type:String,
            required:true
        },
        productImage:{
            type:String,
            default:""
        },
        quantity:{
            type:Number,
            required:true,
            min:1

        },
        unit:{
            type:String,
            default:""
        },
        price:{
            type:Number,
            required:true
        },
        discountPrice:{
            type:Number,
            required:true
        },
        totalPrice:{
            type:Number,
            required:true
        }
    }],
    addressId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Address",
        required:true
    },
    subTotal:{
        type:Number,
        required:true
    },
    deliveryCharges:{
        type:Number,
        default:0
    },
    discountAmount:{
        type:Number,
        default:0
    },
    totalAmount:{
        type:Number,
        required:true
    },
    paymentMethods:{
        type:String,
        enum:["COD","UPI","CARD","NETBANKING"],
        required:true
    },
    paymentStatus:{
        type:String,
        enum:["PENDING","FAILED","SUCCESS","REFUNDED"],
        default:"PENDING"
    },
    status:{
        type:String,
        enum:[
            "PLACED",
            "CONFIRMED",
            "PACKED",
            "SHIPPED",
            "OUT_FOR_DELIVERY",
            "DELIVERED",
            "CANCELED"
        ],
        default:"PLACED"
    },
    deliveredAt:{
        type:Date
    },
    cancelledAt:{
        type:Date
    },
    cancellationReason:{
        type:String,
        default:""
    }

},
    {
        timestams:true
    }
)

module.exports=mongoose.model("Order",orderSchema)